#!/usr/bin/env ruby


require 'date'
require 'fileutils'
require 'net/http'
require 'uri'
require 'cgi'
require 'iconv'

require 'rubygems'
require 'nokogiri'

class Importer

  def initialize(import_file, output_dir)
    @import_file = import_file
    @output_dir  = output_dir
    @crosslinks  = {}
  end

  def import_file
    #doc = REXML::Document.new( File.read( @import_file ) )
    file_content = File.read( @import_file )
    doc = Nokogiri::XML::Document.parse( File.read( @import_file ), 'utf-8' )
    root = doc.root
    #root.get_elements( 'channel/item' ).each do |item|
    root.xpath( './channel/item' ).each do |item|
      import_item( item )
    end
  end

  private

  def import_item(item_xml)
    type = item_xml.xpath( './wp:post_type//text()' ).to_s
    return if type != 'post'

    status = item_xml.xpath( './wp:status//text()' ).to_s
    return if status != 'publish'

    title    = item_xml.xpath( 'title/text()' ).to_s
    author   = 'Bob McWhirter'
    link     = item_xml.xpath( 'link/text()' ).to_s
    if ( link =~ %r(/([^/]+)/$) )
      slug = $1
    end
    @crosslinks[ link.to_s ] = "/blog/#{slug}"
    published = DateTime.parse( item_xml.xpath( 'pubDate/text()' ).to_s )
    output_path = File.join( @output_dir, published.strftime( "%Y-%m-%d-#{slug}.md" ) )
    $stderr.puts "importing #{output_path} #{link} -> #{@crosslinks[link]}"
    content  = item_xml.xpath( 'content:encoded' ).text.to_s.strip
    begin
      content = Iconv.conv( 'iso-8859-1', 'utf8', content )
      begin
        content = Iconv.conv( 'iso-8859-1', 'utf8', content )
      rescue =>e
      end
    rescue =>e 
      # skip iconv
    end
    #content.gsub!(/&/, '&amp; ')
    content.gsub!(/\r/, "\n")
    content.gsub!(/\xa0/, ' ' )

    content = content.gsub( /\n\n\n+/, "\n\n" )

    content = fixup_crosslinks( content )
    content = import_images( content )
    content = import_assets( content )

    tags = item_xml.xpath( "category[@domain='tag' and @nicename]/@nicename" ).collect{|e|e.to_s}

    #if ( ! File.exist?( output_path ) )
      $stderr.puts "writing post: #{output_path}"
      FileUtils.mkdir_p( File.dirname( output_path ) )
      File.open( output_path, 'w' ) do |f|
        #f.puts "date: #{published.year}-#{published.month}-#{published.day}"
        f.puts '---'
        f.puts "title: \"#{title}\""
        f.puts "author: 'Bob McWhirter'"
        f.puts "layout: blog"
        f.puts "tags: [ #{tags.join(', ')} ]"
        f.puts '---'
        f.puts content
      end
    #end
  end
 
  def fixup_crosslinks(content)
    doc = Nokogiri::XML::DocumentFragment.parse( content )
    doc.xpath( './/a' ).each do |a|
      replacement_href = @crosslinks[a['href'].to_s]
      if ( replacement_href )
        a['href'] = replacement_href
      end
    end
    doc.to_s
  end

  def import_images(content)
    doc = Nokogiri::XML::DocumentFragment.parse( content )

    doc.xpath( './/img' ).each do |img|
      src = img['src']
      if ( src =~ /^\// )
        src = "http://bob.mcwhirter.org#{src}"
      end

      basename = File.basename( src )
      output_path = "blog/assets/#{basename}"
 
      if ( ! File.exists?( output_path ) ) 
        url = URI.parse( src )
  
        res = Net::HTTP.start(url.host, url.port) {|http|
          http.get(url.path)
        }
  
        FileUtils.mkdir_p( File.dirname( output_path ) )
        $stderr.puts "writing image: #{output_path}"
        File.open( output_path, 'wb' ) do |f|
          f.write res.body
        end
      end

      img['src'] = "/#{output_path}"
      $stderr.puts "seeking [#{src}]"
      doc.xpath( ".//a" ).each do |a|
        $stderr.puts "check for #{a['href']}"
        href = a['href']
        href = File.join( File.dirname( href ), File.basename( href, File.extname( href ) ) )
        if ( src =~ /^#{href}/ )
          $stderr.puts "replace for #{a['href']}"
          a['href']="/#{output_path}"
        end
      end
    end
    doc.to_s
  end


  def import_assets(content)
    doc = Nokogiri::XML::DocumentFragment.parse( content )

    doc.xpath( '//a' ).each do |a|
      href = a.attributes['href']
      if ( href =~ /^\// )
        href = "http://bob.mcwhirter.org#{href}"
      end
      if ( href =~ /\.(pdf)$/ )
        basename = File.basename( href )
        output_path = "blog/assets/#{basename}"
  
        url = URI.parse( href )
  
        if ( ! File.exist?( output_path ) )
          $stderr.puts "fetching: #{url}"
          FileUtils.mkdir_p( File.dirname( output_path ) )
          File.open( output_path, 'wb' ) do |f|
            Net::HTTP.start(url.host, url.port) do |http|
              http.get(url.path) do |str|
                f.write str
                $stderr.putc '.'
                $stderr.flush
              end
            end
          end
          $stderr.puts "writing asset: #{output_path}"
        end
  
        a['href'] = "/#{output_path}"
      end
    end
    doc.to_s
  end


end

if ( $0 == __FILE__ ) 
  importer = Importer.new( ARGV[0], ARGV[1] )
  importer.import_file
end

